// src/models/Doctor.ts

import { Slot } from './Slot';

/**
 * Doctor model - represents a healthcare provider
 * 
 * Data only, no methods. Slots generated by slotGenerator.
 */
export interface Doctor {
    id: string;
    name: string;
    specialization: string;

    // Schedule configuration
    startTime: string;  // Format: "HH:mm" e.g., "09:00"
    endTime: string;    // Format: "HH:mm" e.g., "17:00"
    slotDurationMinutes: number;
    slotCapacity: number;  // Tokens per slot

    // Generated slots for the day
    slots: Slot[];

    // Emergency governance (optional)
    maxEmergenciesPerSlot?: number;  // Max emergencies per individual slot (default: 1)
    maxEmergenciesPerDay?: number;   // Max emergencies for entire day (default: unlimited)
}
